name: build

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        # java="25" is the LTS Java version used in reproducible builds script (default in Containerfile).
        # More Java versions can be added to test compatibility, eg. "26".
        java: ["25", "26"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: |
          if [ "${{ matrix.java }}" != "25" ]; then
            export OVERRIDE_JAVA_VERSION="${{ matrix.java }}"
          fi
          ./reproducible-builds/build.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: signal-cli-archive-${{ matrix.java }}
          path: dist/*

  build-client:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
          - windows
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v6
      - name: Install rust
        run: rustup default stable
      - name: Build client
        run: cargo build --release --verbose
      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: signal-cli-client-${{ matrix.os }}
          path: |
            client/target/release/signal-cli-client
            client/target/release/signal-cli-client.exe
  build-image:
    needs: build
    runs-on: ubuntu-latest
    # Kør kun image-byg på master-branch eller tags, ikke for hver feature-branch
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v6

      - name: Download signal-cli archive (Java 25)
        uses: actions/download-artifact@v7
        with:
          name: signal-cli-archive-25
          path: dist/

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push custom signal-cli-rest-api image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/signal-cli-rest-api:test
            ghcr.io/${{ github.repository_owner }}/signal-cli-rest-api:${{ github.sha }}
